Basic working version of exec

diff --git a/docker-stack b/docker-stack
--- a/docker-stack
+++ b/docker-stack
@@ -1,13 +1,24 @@
 #!/bin/bash
 set -e
 
+# Defaults
+DEFAULT_PORT=2375
+DEFAULT_EXEC_ARG=bash
+
+# Functions
 function invalid() {
-  echo "ERROR: Unrecognized argument: $1" >&2
-  usage
+  echo "ERROR: Unrecognized argument: ${1}" >&2
+  usage_command
   exit 1
 }
 
-function preprocess {
+function missing() {
+    echo "ERROR: ${1} must be specified" >&2
+    usage_command
+    exit 1
+}
+
+function preprocess() {
 	# Pre-process options to:
 	# - expand -xyz into -x -y -z
 	# - expand --longopt=arg into --longopt arg
@@ -27,31 +38,57 @@ function preprocess {
 }
 
 # Report usage
-function usage() {
+function usage_command() {
     echo
     echo "Usage: $(basename "$0") [OPTIONS] STACK COMMAND [ARG...]"
     echo
     echo "Execute a command in a running service"
     echo
     echo "Options:"
-    echo "  -h, --help              Display command usage help"
-    echo "  -H, --host string       Override the service host"
-    echo "  -P, --port number       Port to connect to host on (default:2375)"
+    echo "  -e, --env list              Set environment variables"
+    echo "  -h, --help                  Display command usage help"
+    echo "  -H, --host string           Override the service host"
+    echo "  -P, --port number           Port to connect to host on (default:$DEFAULT_PORT)"
+    echo "  -p, --project-name string   Project(Stack) name"
+    echo "  -v, --verbose               Print verbose output"
     echo
     echo "Exec"
-    echo "  -e, --env list          Set environment variables"
     echo "  -i, --interactive       Keep STDIN open even if not attached"
     echo "  -t, --tty               Allocate a pseudo-TTY"
     echo "  -u, --user string       Username or UID (format: \"<name|uid>[:<group|gid>]\")"
     echo "  -w, --workdir string    Working directory inside the container"
     echo
     echo "Commands:"
-    echo "  ls          List stacks"
-    echo "  ps          List the tasks in the stack"
-    echo "  services    List the services in the stack"
+    echo "  ls          List stacks."
+    echo "  exec        Execute a command in a running container."
+    echo "  ps          List the tasks in the stack."
+    echo "  services    List the services in the stack."
 }
 
-function parse {
+function parse_command() {
+	# Parse options
+	END_OF_OPT=
+	POSITIONAL=()
+	while [[ $# -gt 0 ]]; do
+        case "${1}" in
+            -e|--env)           shift; ENV_VARS+=("$1") ;;
+            -h|--help)          usage_command; exit 0 ;;
+            -H|--host)          shift; HOST="${1}" ;;
+            -P|--port)          shift; PORT="${1}" ;;
+            -p|--project-name)  shift; STACK="${1}" ;;
+            -v|--verbose)       VERBOSE=1 ;;
+            *)                  COMMAND="${1}"; shift; 
+                                [ -n "$VERBOSE" ] && echo "COMMAND=$COMMAND"
+                                [ -n "$VERBOSE" ] && echo "VERBOSE=$VERBOSE"
+                                break ;;
+        esac
+        shift
+	done
+	# Capture remaining arguments
+    ARGV=( "$@" )
+}
+
+function parse_subcommand() {
     # Preprocess to deal with long_opt=value type parameters
     preprocess "$@"
 
@@ -63,13 +100,15 @@ function parse {
 	POSITIONAL=()
 	while [[ $# -gt 0 ]]; do
 	case "${END_OF_OPT}${1}" in
-		-h|--help)          usage; exit 0 ;;
+		-h|--help)          usage_command; exit 0 ;;
 		-H|--host)          shift; HOST="$1" ;;
 		-P|--port)          shift; PORT="${1}" ;;
+		-s|--stack)         shift; STACK="${1}" ;;
 		-e|--env)           shift; ENV_VARS+=("$1") ;;
         -i|--interactive)   shift; INTERACTIVE=1 ;;
         -t|--tty)           shift; TTY=1 ;;
 		-u|--user)          shift; USERNAME="$1" ;;
+        -v|--verbose)       shift; VERBOSE=1 ;;
         -w|--workdir)       shift; WORKDIR="$1" ;;
 		--)                 END_OF_OPT=1 ;;
 		-*)                 invalid "$1" ;;
@@ -79,47 +118,51 @@ function parse {
 	done
 }
 
-# Parse arguments
-parse "$@"
+
+# Preprocess to deal with long_opt=value type parameters
+preprocess "$@"
+
+# Apply pre-processed options
+set -- "${ARGV[@]}"
+
+# Parse main command
+parse_command "$@"
+
+# Apply remaining arguments
+set -- "${ARGV[@]}"
 
 # Restore the positional arguments
-set -- "${POSITIONAL[@]}"
+#set -- "${POSITIONAL[@]}"
 
 # Application logic
-STACK="$1"; shift
-if [ -z "$STACK" ]; then 
-    echo "ERROR: STACK must be specified"
-    usage
-    exit 1
-fi
-
-COMMAND="$1"; shift
 if [ -z "$COMMAND" ]; then 
-    echo "ERROR: COMMAND must be specified"
-    usage
-    exit 1
+    missing "COMMAND"
 fi
 
-# TODO:
-#   * add --verbose option which prints the commands below
-#   * parse only the arguments required at each command level
-#   * add logs as a command
-#   * use grep to filter the services by stack
-#   * rename to docker-swarm script
-#   * use docker-compose to preprocess yaml files for deployment
 case "$COMMAND" in
-    ls|ps|services)     docker stack $COMMAND $STACK "$@" ;;
+    ls)                 exec docker stack $COMMAND "$@" ;;
+    ps|services)        if [ -z "$STACK" ]; then
+                            missing "STACK"
+                        fi
+                        exec docker stack $COMMAND $STACK "$@" ;;
     exec)               SERVICE="$1"; shift
-                        #echo "SERVICE=$SERVICE"
-                        EXEC_CMD="${@:-bash}"
-                        #echo "EXEC_CMD=$EXEC_CMD"
-                        NODE=$(docker stack ps $STACK --format "{{ .Node }}" | head -n1)
-                        #echo "NODE=$NODE"
-                        CONTAINER=$(docker -H ${HOST:-$NODE}:${PORT:-2375} ps -f name=$STACK_$SERVICE -q | head -n1) 
-                        #echo "CONTAINER=$CONTAINER"
-                        CMD="docker -H ${HOST:-$NODE}:${PORT:-2375} exec -it $CONTAINER $EXEC_CMD"
-                        echo "CMD=$CMD"
-                        $CMD
+                        [ -n "$VERBOSE" ] && echo "SERVICE=$SERVICE"
+                        NODE_CMD="docker stack ps $STACK --format '{{ .Node }}' | head -n1"
+                        [ -n "$VERBOSE" ] && echo "NODE_CMD=$NODE_CMD"
+                        NODE=$(eval "$NODE_CMD")
+                        [ -n "$VERBOSE" ] && echo "NODE=$NODE"
+                        CONTAINER_CMD="docker -H ${HOST:-$NODE}:${PORT:-2375} ps -f name=$STACK_$SERVICE -q | head -n1" 
+                        [ -n "$VERBOSE" ] && echo "CONTAINER_CMD=$CONTAINER_CMD"
+                        CONTAINER=$(eval "$CONTAINER_CMD")
+                        [ -n "$VERBOSE" ] && echo "CONTAINER=$CONTAINER"
+                        EXEC_ARG="${@:-$DEFAULT_EXEC_ARG}"
+                        [ -n "$VERBOSE" ] && echo "EXEC_ARG=$EXEC_ARG"
+                        EXEC_CMD="docker -H ${HOST:-$NODE}:${PORT:-$DEFAULT_PORT} exec -it $CONTAINER $EXEC_ARG"
+                        [ -n "$VERBOSE" ] && echo "EXEC_CMD=$EXEC_CMD"
+                        exec $EXEC_CMD
                         ;;
-    *)                  invalid ;;
+    *)                  invalid "$COMMAND" ;;
 esac
+
+echo "ERROR: Should never see this."
+exit 1
